/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class Colores extends javax.swing.JFrame {

    int rojo = 128, verde = 128, azul = 128;
    public Colores() {
        initComponents();
        this.setTitle("COLORES HEXAGECIMALES Y RGB");
        this.setLocationRelativeTo(null);
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/rgb.png"));
        this.setIconImage(icono);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblColor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBLROJO = new javax.swing.JLabel();
        LBLVERDE = new javax.swing.JLabel();
        LBLAZUL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SLDVERDE = new javax.swing.JSlider();
        SLDAZUL = new javax.swing.JSlider();
        SLDROJO = new javax.swing.JSlider();
        LGLHEXA = new javax.swing.JLabel();
        LGLHEXA1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 470, 410));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setText("VERDE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setText("AZUL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        LBLROJO.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        LBLROJO.setText("128");
        getContentPane().add(LBLROJO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        LBLVERDE.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        LBLVERDE.setText("128");
        getContentPane().add(LBLVERDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        LBLAZUL.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        LBLAZUL.setText("128");
        getContentPane().add(LBLAZUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setText("ROJO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        SLDVERDE.setMajorTickSpacing(1);
        SLDVERDE.setMaximum(255);
        SLDVERDE.setValue(128);
        getContentPane().add(SLDVERDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 30));

        SLDAZUL.setMajorTickSpacing(1);
        SLDAZUL.setMaximum(255);
        SLDAZUL.setValue(128);
        getContentPane().add(SLDAZUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 240, 30));

        SLDROJO.setMajorTickSpacing(1);
        SLDROJO.setMaximum(255);
        SLDROJO.setValue(128);
        getContentPane().add(SLDROJO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, 30));

        LGLHEXA.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        LGLHEXA.setText("RGB");
        getContentPane().add(LGLHEXA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 350, -1));

        LGLHEXA1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        LGLHEXA1.setText("HEXA");
        getContentPane().add(LGLHEXA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 350, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLAZUL;
    private javax.swing.JLabel LBLROJO;
    private javax.swing.JLabel LBLVERDE;
    private javax.swing.JLabel LGLHEXA;
    private javax.swing.JLabel LGLHEXA1;
    private javax.swing.JSlider SLDAZUL;
    private javax.swing.JSlider SLDROJO;
    private javax.swing.JSlider SLDVERDE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblColor;
    // End of variables declaration//GEN-END:variables
}
